#ifndef TRIP_H
#define TRIP_H

#include <string>
#include <vector>

// This is the structure used to return routes.
// Do not edit this file.

struct Trip {
  struct Leg {
    std::string line; // What transit line do you take?
    std::string stop; // What station do you get off at?
  };

  std::string      start; // What station do you start at?
  std::vector<Leg> legs;  // Each leg of the trip, in order.
};

#endif
