#ifndef STAR_H
#define STAR_H

// Use this class to return stars from your find function.
// Use it to represent stars internally if you want.
// Do not edit this file.

struct Star {
    int   id;
    float x;
    float y;
    float z;
};

#endif
