#ifndef DICTIONARY_H
#define DICTIONARY_H

#include <cstddef>
#include <istream>
#include <string>
#include <vector>

#include "Heap.h"
#include "Point.h"

// This is the dictionary class you need to implement.
// It stores a list of words, and predicts words from keypress points.
// Do not edit this file.


class Dictionary {
    std::vector<std::string> mWords;

public:
    Dictionary(std::istream& stream);

    Heap correct(const std::vector<Point>& points, size_t maxcount, float cutoff) const;
};

#endif
